### ISSUE TITLE
Dashboard showing action that was not performed

### ISSUE THREAD

**Issue by jadjoubran** [VarCI/support#2]
Screenshot attached 
[Issue link](https://github.com/jadjoubran/laravel5-angular-material-starter/issues/347)
<img width="1280" alt="screen shot 2016-06-30 at 4 10 46 pm" src="https://cloud.githubusercontent.com/assets/2265232/16489236/505a3d32-3edd-11e6-96b4-42e4a483ddf3.png">

**Comment by jadb** [comment]
@jadjoubran this should be fixed by now. Can you confirm/close when you get a chance please?

**Comment by jadjoubran** [comment]
I can confirm it's working, thanks! 😄
