### ISSUE TITLE
500 Server error after "Request Access"

### ISSUE THREAD

**Issue by nWidart** [VarCI/support#5]
Hello,

I got an email inviting me to the service 08th of August.
Today I wanted to login again and misclicked, clicked the "Request Access" link.
When I afterwards tried to login again, it's showing me an error 500 page with the following error:
<img width="986" alt="screen shot 2016-08-09 at 09 35 13" src="https://cloud.githubusercontent.com/assets/882397/17523894/85804b0c-5e5c-11e6-9b1e-4951a49503f2.png">

Thanks,

**Comment by jadb** [comment]
@nWidart, can you please check now?

**Comment by nWidart** [comment]
Thanks, it worked. 👍

**Comment by jadb** [comment]
Thanks for helping during this beta period! 😊
